# Generated by Django 5.1.4 on 2025-01-01 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='events',
        ),
        migrations.AlterModelTable(
            name='eventparticipant',
            table='event_participant',
        ),
        migrations.AlterModelTable(
            name='participant',
            table='participants',
        ),
    ]
