# Generated by Django 5.1.4 on 2025-01-03 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0003_rename_event_id_eventparticipant_event_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventparticipant',
            unique_together=set(),
        ),
    ]
