# Generated by Django 5.1.4 on 2025-01-03 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0004_alter_eventparticipant_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventparticipant',
            unique_together={('event', 'participant')},
        ),
    ]
