# Generated by Django 5.1.4 on 2025-01-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('users', models.ManyToManyField(to='event_management.authuserapi')),
            ],
            options={
                'db_table': 'auth_permission',
            },
        ),
    ]
