# Generated by Django 5.1.4 on 2025-01-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0004_alter_permission_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='method',
            field=models.CharField(default='GET', max_length=6),
        ),
        migrations.AddField(
            model_name='permission',
            name='route',
            field=models.CharField(default='', max_length=100),
        ),
    ]
