# Generated by Django 5.1.4 on 2025-01-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0006_alter_event_event_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUserApi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'api_users',
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_management/storage/event_covers/'),
        ),
    ]
