# Generated by Django 5.1.4 on 2025-01-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0008_alter_authuserapi_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuserapi',
            name='email',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
