# Generated by Django 5.1.4 on 2025-01-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0008_eventparticipant_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipant',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='modules/event_management/storage/event_qr_codes/'),
        ),
    ]
