# Generated by Django 5.1.4 on 2025-01-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0009_alter_eventparticipant_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='empty_slot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
