# Generated by Django 5.1.4 on 2025-01-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0011_alter_authuserapi_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover_disk_storage',
            field=models.CharField(default='local', max_length=20),
        ),
    ]
